START TRANSACTION
;
DROP TABLE IF EXISTS oscalert_log
;
CREATE TABLE IF NOT EXISTS oscalert_log (
  id SERIAL,
  timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  content VARCHAR(510) NOT NULL,
  PRIMARY KEY(id)
)
ENGINE = InnoDB
;
COMMIT