START TRANSACTION
;
ALTER TABLE `field_situation` 
  ADD COLUMN `num_acarts` SMALLINT UNSIGNED NOT NULL DEFAULT '0'
,
  ADD COLUMN `num_matvs` SMALLINT UNSIGNED NOT NULL DEFAULT '0'
,
  ADD COLUMN `num_mbks` SMALLINT UNSIGNED NOT NULL DEFAULT '0'
;
COMMIT